import type { CourseModule } from '../../types';

export const recursionDp: CourseModule = {
  id: 'recursion-dp',
  title: 'Recursion, Backtracking & DP',
  track: 'core',
  status: 'outline',
  source: 'Chapter 8',
  summary:
    'Design the recursive case, then decide whether to memoise it, tabulate it, or prune it with backtracking.',
  estimatedMinutes: 100,
  concepts: [
    'Spotting recursive problems: "compute the nth…", "list all…", "count all ways…"',
    'Three ways to find the recursion: build up from the smallest case, break the problem down from the top, or split it in half and combine',
    'Defining the base case so it is reached and is correct',
    'Shrinking the state on every call, so the recursion terminates',
    'Recursion always costs O(depth) stack space; every recursion has an iterative form',
    'Overlapping subproblems as the signal for memoisation',
    'Top-down memoisation vs bottom-up tabulation, and the space each needs',
    'Rolling arrays: keeping only the last row or last two values',
    'State-key design - what exactly identifies a subproblem',
    'Backtracking as choose / recurse / unchoose',
    'Pruning: abandoning a branch the moment it cannot lead to an answer',
    'Generating subsets recursively and via bit masks',
    'Generating permutations, with and without duplicate characters',
    'Counting the ways instead of enumerating them, when only the count is asked for',
    'Grid path counting and reachability with obstacles',
    'Flood fill and connected regions',
    'Optimal substructure in stacking, partitioning and expression problems',
    'Recursive halving: multiply, power and magic index via divide and conquer',
    'Towers of Hanoi as the model recursive construction',
  ],
  plannedAnimations: [
    'A recursion tree unfolding, with memoised nodes lighting up as cache hits',
    'A DP table filling cell by cell, with arrows to the cells each value depends on',
    'Backtracking on n-queens: place, detect a conflict, unchoose, try the next column',
    'Subset generation by counting in binary, bit by bit',
    'Coin change: the same subproblem reached by three different paths',
  ],
  sections: [],
  quiz: [],
  drills: [
    { slug: 'climbing-stairs', note: 'CTCI 8.1 - the "hello world" of DP. Do all four versions.' },
    { slug: 'coin-change', note: 'Minimising, not counting. Know the difference from CTCI 8.11.' },
    { slug: 'house-robber', note: 'CTCI 17.16 - non-adjacent maximum.' },
    { slug: 'house-robber-ii', note: 'Same, in a circle - run it twice with one house excluded.' },
    { slug: 'longest-increasing-subsequence', note: 'O(n²) DP, then the O(n log n) patience version.' },
    { slug: 'longest-common-subsequence', note: 'The two-dimensional table to know cold.' },
    { slug: 'word-break', note: 'CTCI 17.13 - memoise on the suffix index.' },
    { slug: 'combination-sum-iv', note: 'Order matters here - notice it changes the recurrence.' },
    { slug: 'decode-ways', note: 'Careful base cases and zero handling.' },
    { slug: 'unique-paths', note: 'The plainest grid DP.' },
    { slug: 'unique-paths-ii', note: 'CTCI 8.2 - the same grid with obstacles.' },
    { slug: 'jump-game', note: 'Greedy beats DP - work out why.' },
    { slug: 'maximum-subarray', note: 'CTCI 16.17 - Kadane. Say the DP framing.' },
    { slug: 'maximum-product-subarray', note: 'Track the running minimum too, because of negatives.' },
    { slug: 'subsets', note: 'CTCI 8.4 - recursion and the bit-mask version.' },
    { slug: 'permutations', note: 'CTCI 8.7 - choose / recurse / unchoose.' },
    { slug: 'combination-sum', note: 'Backtracking with reuse and a start index.' },
    { slug: 'generate-parentheses', note: 'CTCI 8.9 - track open and close counts remaining.' },
    { slug: 'n-queens', note: 'CTCI 8.12 - the canonical pruning problem.' },
    { slug: 'word-search', note: 'Backtracking on a grid with an in-place visited marker.' },
    { slug: 'flood-fill', note: 'CTCI 8.10 - paint fill.' },
    { slug: 'edit-distance', note: 'The other two-dimensional table to know cold.' },
    { slug: 'partition-equal-subset-sum', note: 'Subset sum as a boolean DP.' },
    { slug: 'min-cost-climbing-stairs', note: 'A gentle rolling-array exercise.' },
    { slug: 'target-sum', note: 'Counting sign assignments - memoise on (index, runningSum).' },
    { slug: 'russian-doll-envelopes', note: 'CTCI 8.13 and 17.8 - sort, then LIS on the other dimension.' },
    { slug: 'different-ways-to-add-parentheses', note: 'CTCI 8.14 - split at every operator.' },
    { slug: 'coin-change-ii', note: 'CTCI 8.11 - counting combinations, where order does not matter.' },
    { slug: 'permutations-ii', note: 'CTCI 8.8 - branch on counts to avoid duplicates.' },
    { slug: 'fixed-point', note: 'CTCI 8.3 - magic index by binary search. Premium.' },
    { slug: 'largest-1-bordered-square', note: 'CTCI 17.23 - precompute runs, then test squares.' },
    { slug: 'max-sum-of-rectangle-no-larger-than-k', note: 'CTCI 17.24 - fix a row pair, then Kadane.' },
  ],
};
