import type { CourseModule } from '../../types';

export const sortingSearching: CourseModule = {
  id: 'sorting-searching',
  title: 'Sorting & Searching',
  track: 'core',
  status: 'outline',
  source: 'Chapter 10',
  summary:
    'The sorts worth knowing, binary search on things that are not quite sorted, and searching data that will not fit in memory.',
  estimatedMinutes: 75,
  concepts: [
    'Bubble and selection sort: O(n²), worth knowing only as a baseline',
    'Merge sort: O(n log n) always, stable, O(n) auxiliary space',
    'Quicksort: O(n log n) expected, O(n²) worst, in place, not stable; pivot choice matters',
    'Radix sort: O(kn) for fixed-width integers - beating the comparison bound by not comparing',
    'Counting and bucket sorts when the value range is small and known',
    'Stability, in-place behaviour, worst case and auxiliary space as the four axes to compare on',
    'Binary search and its boundary conditions: inclusive vs exclusive bounds, overflow-safe midpoints',
    'Finding the first or last occurrence rather than any occurrence',
    'Binary search on a rotated array: work out which half is sorted, then decide',
    'Duplicates degrading rotated search to O(n)',
    'Exponential probing to find the length of a structure with no size method',
    'Searching sorted data with gaps, by walking to the nearest non-empty entry',
    'External merge sort for files far larger than memory',
    'Bit vectors and chunked counting passes under strict memory limits',
    'Eliminating a row or column per step in a row/column-sorted matrix',
    'Augmenting a BST with subtree sizes for online rank queries',
    'Sorting as preprocessing: the interval, closest-pair and sweep-line patterns',
    'Local rearrangement into alternating peaks and valleys without a full sort',
  ],
  plannedAnimations: [
    'Merge sort splitting and merging, with the auxiliary array visible',
    'Quicksort partitioning around a pivot, with the worst-case pivot shown alongside',
    'Binary search on a rotated array, highlighting which half is sorted at each step',
    'Corner-walking search on a row/column-sorted matrix, eliminating a line each step',
    'External merge sort: chunks sorted in memory, then k-way merged',
  ],
  sections: [],
  quiz: [],
  drills: [
    { slug: 'binary-search', note: 'Write it with no off-by-one. Then write the first-occurrence variant.' },
    { slug: 'search-in-rotated-sorted-array', note: 'CTCI 10.3 - decide which half is sorted first.' },
    { slug: 'find-minimum-in-rotated-sorted-array', note: 'The same reasoning, looking for the pivot.' },
    { slug: 'group-anagrams', note: 'CTCI 10.2 - a canonical key beats comparing pairs.' },
    { slug: 'merge-intervals', note: 'Sort by start, then sweep. The interval template.' },
    { slug: 'insert-interval', note: 'Same family, without needing the sort.' },
    { slug: 'non-overlapping-intervals', note: 'Greedy by end time - prove why that is optimal.' },
    { slug: 'meeting-rooms', note: 'Sort and check adjacency. Premium.' },
    { slug: 'meeting-rooms-ii', note: 'Sweep line or a heap of end times. Premium.' },
    { slug: 'search-a-2d-matrix-ii', note: 'CTCI 10.9 - start from a corner.' },
    { slug: 'find-peak-element', note: 'Binary search with no sorted array in sight.' },
    { slug: 'search-insert-position', note: 'Lower-bound binary search.' },
    { slug: 'single-element-in-a-sorted-array', note: 'Binary search on parity of indices.' },
    { slug: 'median-of-two-sorted-arrays', note: 'Hard - binary search on the partition point.' },
    { slug: 'sort-an-array', note: 'Implement merge sort and quicksort by hand.' },
    { slug: 'h-index', note: 'Counting sort makes it O(n).' },
    { slug: 'merge-sorted-array', note: 'CTCI 10.1 - fill from the back.' },
    { slug: 'first-missing-positive', note: 'CTCI 10.7 - index-as-hash, O(1) space.' },
    { slug: 'minimum-absolute-difference', note: 'CTCI 16.6 - sort, then a single scan.' },
    { slug: 'maximum-population-year', note: 'CTCI 16.10 - the delta/sweep trick.' },
    { slug: 'count-of-smaller-numbers-after-self', note: 'CTCI 10.10 - augmented BST or merge sort.' },
    { slug: 'wiggle-sort', note: 'CTCI 10.11 - local swaps, no full sort needed. Premium.' },
    { slug: 'search-in-rotated-sorted-array-ii', note: 'The duplicate case that breaks the clean O(log n).' },
  ],
};
