import type { CourseModule } from '../../types';

export const bitManipulation: CourseModule = {
  id: 'bit-manipulation',
  title: 'Bit Manipulation',
  track: 'core',
  status: 'outline',
  source: 'Chapter 5',
  summary:
    'Masks, shifts and two\'s complement - plus the handful of tricks that turn arithmetic problems into one-liners.',
  estimatedMinutes: 60,
  concepts: [
    'Binary representation and doing binary addition, subtraction and multiplication by hand',
    "Two's complement: negation is invert-then-add-one; the sign bit",
    'Arithmetic vs logical right shift (>> vs >>> in JavaScript) and when the difference bites',
    'AND, OR, XOR, NOT and the identities worth memorising (x ^ 0 = x, x ^ x = 0, x & (x−1))',
    'The four mask operations: get, set, clear and update a bit',
    'Clearing all bits above or below a position with a shifted mask',
    'n & (n−1) clears the lowest set bit - so it tests powers of two and counts set bits',
    'XOR to count differing bits, and to cancel out paired values',
    'Isolating and moving runs of ones',
    'Bit vectors: packing booleans into integers, and byte-packed bitmap addressing',
    'JavaScript specifics: bitwise operators coerce to 32-bit signed integers; BigInt for more',
    'Adding without the plus operator: XOR for the sum, AND-and-shift for the carry',
    'Building subsets by counting in binary',
  ],
  plannedAnimations: [
    'A mask being built, shifted and applied - get/set/clear/update side by side',
    "Two's complement negation, bit by bit",
    'n & (n−1) repeatedly clearing the lowest set bit until the value is zero',
    'Bitwise addition: XOR and carry converging over several rounds',
    'A byte-packed screen buffer with a horizontal line being drawn across byte boundaries',
  ],
  sections: [],
  quiz: [],
  drills: [
    { slug: 'number-of-1-bits', note: 'Do it with n & (n−1) and count the iterations.' },
    { slug: 'counting-bits', note: 'The DP relation using the lowest bit.' },
    { slug: 'reverse-bits', note: 'Careful with unsigned handling in JavaScript.' },
    { slug: 'missing-number', note: 'CTCI 17.4 - XOR or the sum formula.' },
    { slug: 'sum-of-two-integers', note: 'CTCI 17.1 - add without +.' },
    { slug: 'single-number', note: 'XOR cancellation in its purest form.' },
    { slug: 'single-number-ii', note: 'Counting bits mod 3 - the generalisation.' },
    { slug: 'power-of-two', note: 'CTCI 5.5 - exactly the n & (n−1) test.' },
    { slug: 'bitwise-and-of-numbers-range', note: 'The common prefix of the range.' },
    { slug: 'add-binary', note: 'Manual carry propagation on strings.' },
    { slug: 'max-consecutive-ones-iii', note: 'CTCI 5.3 - flip-one-zero as a sliding window.' },
    { slug: 'hamming-distance', note: 'CTCI 5.6 - XOR then popcount.' },
    { slug: 'divide-two-integers', note: 'CTCI 16.9 - division by shifting.' },
  ],
};
