import type { CourseModule } from '../../types';

export const heapsTries: CourseModule = {
  id: 'heaps-tries',
  title: 'Heaps & Tries',
  track: 'core',
  status: 'outline',
  source: 'Chapter 4 (heaps and tries)',
  summary:
    'Two structures that turn hard problems easy: heaps for "top k" and streaming order, tries for prefix work.',
  estimatedMinutes: 50,
  concepts: [
    'Min-heap and max-heap as complete binary trees stored in an array',
    'Array index arithmetic: children at 2i+1 and 2i+2, parent at (i−1)/2',
    'Insert then bubble up; extract-min then bubble down - both O(log n)',
    'Peek is O(1); building a heap from an array is O(n), not O(n log n)',
    'A heap gives you the extreme, never the sorted order - use it when you only need the top',
    'Top-k with a heap of size k: O(n log k) time and O(k) space',
    'Two heaps balanced around the centre for a streaming median',
    'Heaps for merging k sorted sequences',
    'Tries: prefix trees where each edge is a character and each node marks whether a word ends there',
    'Trie lookup is O(length of the key), independent of how many words are stored',
    'Tries answer "is this a valid prefix?" - which is what makes them prune backtracking so well',
    'Space cost of a trie, and the child-map vs fixed-array tradeoff',
    'Tries for multi-pattern search and for word-grid problems',
  ],
  plannedAnimations: [
    'Heap insert bubbling up, and extract-min sifting down, with the array view beside the tree view',
    'Two heaps rebalancing as a stream arrives, median highlighted between the roots',
    'A trie growing word by word, then a prefix query walking down it',
    'Backtracking on a grid, pruned the moment the trie says the prefix is dead',
  ],
  sections: [],
  quiz: [],
  drills: [
    { slug: 'top-k-frequent-elements', note: 'Count with a map, then a heap of size k (or bucket sort for O(n)).' },
    { slug: 'find-median-from-data-stream', note: 'CTCI 17.20 - the two-heap answer.' },
    { slug: 'merge-k-sorted-lists', note: 'The heap solution: O(n log k).' },
    { slug: 'implement-trie-prefix-tree', note: 'Build it from scratch once.' },
    { slug: 'design-add-and-search-words-data-structure', note: 'Trie plus wildcard recursion.' },
    { slug: 'word-search-ii', note: 'CTCI 17.25-adjacent - trie-pruned backtracking on a grid.' },
    { slug: 'last-stone-weight', note: 'The simplest possible max-heap loop.' },
    { slug: 'k-closest-points-to-origin', note: 'Heap of size k, or quickselect.' },
    { slug: 'task-scheduler', note: 'Greedy with counts - a heap makes it obvious.' },
    { slug: 'kth-largest-element-in-a-stream', note: 'A min-heap of size k, maintained online.' },
    { slug: 'design-twitter', note: 'Merging k feeds with a heap.' },
    { slug: 'ugly-number-ii', note: 'CTCI 17.9 - generate in order with a heap or three queues.' },
    { slug: 'concatenated-words', note: 'CTCI 17.15 - trie plus memoised splitting.' },
    { slug: 'stream-of-characters', note: 'CTCI 17.17 - multi-pattern search with a suffix trie.' },
    { slug: 'letter-combinations-of-a-phone-number', note: 'CTCI 16.20 - the T9 mapping.' },
  ],
};
