import type { CourseModule } from '../../types';

export const mathLogic: CourseModule = {
  id: 'math-logic',
  title: 'Math & Logic Puzzles',
  track: 'techniques',
  status: 'outline',
  source: 'Chapter 6',
  summary:
    'Primes, probability, invariants and the disciplined way to attack a puzzle when there is no algorithm to reach for.',
  estimatedMinutes: 60,
  concepts: [
    'Prime testing up to √n, and why the square root is enough',
    'The Sieve of Eratosthenes for generating primes in a range',
    'Prime factorisation, divisibility, GCD and LCM',
    'Probability of independent events (multiply) and mutually exclusive ones (add)',
    'Conditional probability, and using the complement when the direct count is messy',
    'Information theory in disguise: how many outcomes can one measurement distinguish?',
    'Encoding identity in binary across parallel tests (the poison-bottle pattern)',
    'Weighted measurement: give each candidate a different count so the total identifies it',
    'Invariants and impossibility proofs - colouring arguments and parity',
    'State-space search for constructive puzzles',
    'Worst-case minimisation and decision-tree depth',
    'Balancing the worst case by making early steps costlier (the egg-drop pattern)',
    'Perfect squares as the numbers with an odd divisor count',
    'Rejection sampling to build a uniform distribution from another one',
    'Fisher-Yates shuffling, and reservoir sampling for unknown-length streams',
    'Stating assumptions explicitly, starting from small cases, and looking for the pattern',
  ],
  plannedAnimations: [
    'The sieve crossing out multiples, prime by prime',
    'A decision tree for the egg-drop problem, showing worst-case depth shrinking as the first drop moves',
    'Rejection sampling: the discarded region of the outcome grid, and why what remains is uniform',
    'Fisher-Yates swapping backwards, with each position finalised in turn',
    'The mutilated chessboard colouring argument',
  ],
  sections: [],
  quiz: [],
  drills: [
    { slug: 'count-primes', note: 'Implement the sieve and state its complexity.' },
    { slug: 'happy-number', note: 'Cycle detection applied to arithmetic.' },
    { slug: 'factorial-trailing-zeroes', note: 'CTCI 16.5 - count the factors of five.' },
    { slug: 'powx-n', note: 'Fast exponentiation by halving.' },
    { slug: 'excel-sheet-column-number', note: 'Base conversion with an awkward offset.' },
    { slug: 'implement-rand10-using-rand7', note: 'CTCI 16.23 - rejection sampling.' },
    { slug: 'random-pick-with-weight', note: 'Prefix sums plus binary search.' },
    { slug: 'water-and-jug-problem', note: 'CTCI 6.5 - state search, or the GCD insight.' },
    { slug: 'super-egg-drop', note: 'CTCI 6.8 - the full DP version.' },
    { slug: 'bulb-switcher', note: 'CTCI 6.9 - only perfect squares survive.' },
    { slug: 'poor-pigs', note: 'CTCI 6.10 - binary encoding across tests.' },
    { slug: 'shuffle-an-array', note: 'CTCI 17.2 - Fisher-Yates, and why the naive shuffle is biased.' },
    { slug: 'linked-list-random-node', note: 'CTCI 17.3 - reservoir sampling.' },
    { slug: 'number-of-digit-one', note: 'CTCI 17.6 - count per digit position.' },
    { slug: 'set-mismatch', note: 'CTCI 17.19 - recover missing values from sums.' },
    { slug: 'max-points-on-a-line', note: 'CTCI 16.14 - slopes as hash keys, with the precision trap.' },
  ],
};
