import type { CourseModule } from '../../types';

export const treesGraphs: CourseModule = {
  id: 'trees-graphs',
  title: 'Trees & Graphs',
  track: 'core',
  status: 'outline',
  source: 'Chapter 4',
  summary:
    'Tree shapes, the three traversals, BFS vs DFS, and the graph problems that hide inside tree questions.',
  estimatedMinutes: 90,
  concepts: [
    'Tree vocabulary: root, child, leaf, no cycles - and that a tree is a kind of graph',
    'Binary tree vs binary search tree, and clarifying which one you have been given',
    'Complete, full and perfect trees, and the node counts that follow',
    'Balanced vs unbalanced, and why "balanced" only promises O(log n), not perfection',
    'In-order, pre-order and post-order traversal, and what each is used for',
    'Adjacency list vs adjacency matrix, and when the matrix is worth the O(V²) space',
    'Directed vs undirected graphs; connected components; forests',
    'DFS: recursive or explicit stack, low memory, goes deep, good for exhaustive search',
    'BFS: queue-based, finds shortest unweighted paths, good for "closest" questions',
    'Bidirectional search and why it shrinks the frontier so dramatically',
    'Visited sets, and that graphs need them where trees do not',
    'Building a minimum-height BST from sorted data by repeatedly taking the middle',
    'Validating a BST with min/max bounds rather than local comparisons',
    'Height propagation for balance checks in a single pass',
    'In-order successor with and without parent pointers',
    'Topological sort and cycle detection for dependency ordering',
    'Lowest common ancestor, with and without parent links',
    'Subtree matching, including the string-serialisation trick',
    'Prefix sums along a root-to-node path for path-sum counting',
    'Uniform random selection from a mutable tree using subtree sizes',
  ],
  plannedAnimations: [
    'BFS wave vs DFS dive on the same graph, side by side',
    'The three traversals producing three different orders on one tree',
    'BST validation with the min/max bound window narrowing as you descend',
    'Topological sort by indegree, with the queue draining',
    'Bidirectional search - two frontiers meeting in the middle',
  ],
  sections: [],
  quiz: [],
  drills: [
    { slug: 'maximum-depth-of-binary-tree', note: 'The warm-up recursion.' },
    { slug: 'same-tree', note: 'Structural comparison - the base of subtree matching.' },
    { slug: 'invert-binary-tree', note: 'Two lines, but say the complexity out loud.' },
    { slug: 'binary-tree-level-order-traversal', note: 'CTCI 4.3 - BFS with level boundaries.' },
    { slug: 'validate-binary-search-tree', note: 'CTCI 4.5 - bounds, not local comparisons.' },
    { slug: 'lowest-common-ancestor-of-a-binary-search-tree', note: 'Use the ordering; it is much easier than the general tree.' },
    { slug: 'binary-tree-maximum-path-sum', note: 'Return one value, track another - the classic two-value recursion.' },
    { slug: 'serialize-and-deserialize-binary-tree', note: 'Pre-order with null markers.' },
    { slug: 'subtree-of-another-tree', note: 'CTCI 4.10.' },
    { slug: 'construct-binary-tree-from-preorder-and-inorder-traversal', note: 'Why you need two traversals to reconstruct.' },
    { slug: 'kth-smallest-element-in-a-bst', note: 'In-order traversal is sorted order.' },
    { slug: 'clone-graph', note: 'A map from old node to new node is the whole trick.' },
    { slug: 'course-schedule', note: 'CTCI 4.7 - cycle detection on a dependency graph.' },
    { slug: 'number-of-islands', note: 'Grid as graph. DFS or BFS both work.' },
    { slug: 'pacific-atlantic-water-flow', note: 'Search backwards from the edges, not forwards from each cell.' },
    { slug: 'alien-dictionary', note: 'Topological sort in disguise. Premium.' },
    { slug: 'graph-valid-tree', note: 'Connected and exactly n−1 edges. Premium.' },
    { slug: 'number-of-connected-components-in-an-undirected-graph', note: 'Union-find or repeated DFS. Premium.' },
    { slug: 'balanced-binary-tree', note: 'CTCI 4.4 - do it in one pass, not O(n log n).' },
    { slug: 'diameter-of-binary-tree', note: 'Same two-value recursion as max path sum.' },
    { slug: 'path-sum-iii', note: 'CTCI 4.12 - running prefix sums in a map.' },
    { slug: 'lowest-common-ancestor-of-a-binary-tree', note: 'CTCI 4.8 - the general case.' },
    { slug: 'binary-tree-right-side-view', note: 'BFS, taking the last node of each level.' },
    { slug: 'rotting-oranges', note: 'Multi-source BFS - the "wave" made literal.' },
    { slug: 'convert-sorted-array-to-binary-search-tree', note: 'CTCI 4.2 - minimal height by construction.' },
    { slug: 'inorder-successor-in-bst', note: 'CTCI 4.6. Premium.' },
    { slug: 'binary-tree-inorder-traversal', note: 'Then do it iteratively with an explicit stack.' },
    { slug: 'find-if-path-exists-in-graph', note: 'CTCI 4.1 - plain reachability.' },
    { slug: 'accounts-merge', note: 'CTCI 17.7 - components over a synonym graph.' },
    { slug: 'word-ladder', note: 'CTCI 17.22 - BFS over word transformations.' },
    { slug: 'max-area-of-island', note: 'CTCI 16.19 - flood fill returning a size.' },
    { slug: 'convert-binary-search-tree-to-sorted-doubly-linked-list', note: 'CTCI 17.12. Premium.' },
  ],
};
