/**
 * Generates COVERAGE.md from the content data, so the file cannot drift.
 *
 *   pnpm gen:coverage
 *
 * `src/data/coverage.test.ts` re-checks the result, so a stale COVERAGE.md
 * fails `pnpm check` rather than silently lying.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { MODULES } from '../src/content';
import { TRACKS } from '../src/content/types';
import { BOOK_QUESTIONS } from '../src/data/questions';
import { BLIND_75, getProblem, leetcodeUrl } from '../src/data/problems';
import { SPRINT_WEEKS } from '../src/data/sprint';

const moduleTitle = (id: string) => MODULES.find((m) => m.id === id)?.title ?? id;

const lines: string[] = [];
const push = (line = '') => lines.push(line);

push('# Coverage');
push();
push(
  'Generated by `pnpm gen:coverage` from the content data. Do not edit by hand - ' +
    '`src/data/coverage.test.ts` fails if this file and the data disagree.',
);
push();
push(
  `Every chapter of Cracking the Coding Interview (6th edition) maps to a dojo module, ` +
    `all ${BOOK_QUESTIONS.length} questions are indexed, and all ${BLIND_75.length} of 75 ` +
    `Blind 75 problems are assigned to exactly one module's drill list.`,
);
push();

// ---------------------------------------------------------------- summary
const complete = MODULES.filter((m) => m.status === 'complete');
const outline = MODULES.filter((m) => m.status === 'outline');
push('## Status at a glance');
push();
push('| | Count |');
push('|---|---:|');
push(`| Modules | ${MODULES.length} |`);
push(`| Fully written (lesson + animations + audio + quiz + drills) | ${complete.length} |`);
push(`| Structured outline (concepts + drills, content coming) | ${outline.length} |`);
push(`| Book questions indexed | ${BOOK_QUESTIONS.length} |`);
push(
  `| Questions with a LeetCode equivalent | ${BOOK_QUESTIONS.filter((q) => q.leetcode).length} |`,
);
push(`| Questions that are book-only | ${BOOK_QUESTIONS.filter((q) => !q.leetcode).length} |`);
push(`| Blind 75 assigned | ${BLIND_75.length} of 75 |`);
push(
  `| Total drill problems across all modules | ${new Set(MODULES.flatMap((m) => m.drills.map((d) => d.slug))).size} |`,
);
push();

// ------------------------------------------------------- chapter -> module
push('## Book chapter to module');
push();
push('| Book source | Module | Track | Status | Questions | Drills |');
push('|---|---|---|---|---:|---:|');
for (const track of TRACKS) {
  for (const courseModule of MODULES.filter((m) => m.track === track.id)) {
    const questionCount = BOOK_QUESTIONS.filter((q) => q.moduleId === courseModule.id).length;
    const drillCount = courseModule.drills.length + (courseModule.practice?.length ?? 0);
    push(
      `| ${courseModule.source} | ${courseModule.title} \`${courseModule.id}\` | ${track.label} | ` +
        `${courseModule.status === 'complete' ? 'Complete' : 'Outline'} | ${questionCount} | ${drillCount} |`,
    );
  }
}
push();
push(
  '"Questions" counts the book questions whose *technique* this module teaches. For chapters 16 ' +
    'and 17 the book deliberately hides the technique, so those questions point at the module that ' +
    'teaches the tool they need rather than at the mixed-review module itself.',
);
push();

// ------------------------------------------------------------ sprint plan
push('## Five-week sprint');
push();
push('| Week | Dates | Focus | Modules |');
push('|---|---|---|---|');
for (const week of SPRINT_WEEKS) {
  push(
    `| ${week.label} | ${week.dateLabel} | ${week.focus} | ${week.moduleIds.map(moduleTitle).join(', ')} |`,
  );
}
push();
const scheduled = new Set(SPRINT_WEEKS.flatMap((w) => w.moduleIds));
push(
  `Unscheduled (float): ${MODULES.filter((m) => !scheduled.has(m.id))
    .map((m) => m.title)
    .join(', ')}.`,
);
push();

// ------------------------------------------------------------- Blind 75
push('## Blind 75 assignment');
push();
push('Each problem appears in exactly one module drill list.');
push();
push('| # | Problem | Difficulty | Module |');
push('|---:|---|---|---|');
const ownerOf = new Map<string, string>();
for (const courseModule of MODULES) {
  for (const drill of courseModule.drills) {
    if (getProblem(drill.slug)?.blind75) ownerOf.set(drill.slug, courseModule.id);
  }
}
BLIND_75.forEach((problem, index) => {
  push(
    `| ${index + 1} | [${problem.title}](${leetcodeUrl(problem.slug)})${problem.premium ? ' _(premium)_' : ''} | ` +
      `${problem.difficulty} | ${moduleTitle(ownerOf.get(problem.slug) ?? '?')} |`,
  );
});
push();

// ------------------------------------------------------------ 189 questions
push('## All 189 book questions');
push();
const chapters = [...new Set(BOOK_QUESTIONS.map((q) => q.chapter))];
for (const chapter of chapters) {
  const questions = BOOK_QUESTIONS.filter((q) => q.chapter === chapter);
  push(`### ${chapter}`);
  push();
  push('| ID | Title | Gist | Taught in | Closest LeetCode |');
  push('|---|---|---|---|---|');
  for (const question of questions) {
    const lc = question.leetcode
      ? `[${question.leetcode.title}](${leetcodeUrl(question.leetcode.slug)})`
      : '_book-only_';
    push(
      `| ${question.id} | ${question.title} | ${question.gist} | ${moduleTitle(question.moduleId)} | ${lc} |`,
    );
  }
  push();
}

// --------------------------------------------------------- module details
push('## Module detail');
push();
for (const courseModule of MODULES) {
  push(`### ${courseModule.title} \`${courseModule.id}\``);
  push();
  push(
    `- Source: ${courseModule.source} · Track: ${TRACKS.find((t) => t.id === courseModule.track)?.label} · ` +
      `Status: ${courseModule.status === 'complete' ? 'Complete' : 'Outline'}`,
  );
  push(`- ${courseModule.summary}`);
  push(
    `- Concepts listed: ${courseModule.concepts.length} · Lesson sections: ${courseModule.sections.length} · ` +
      `Quiz questions: ${courseModule.quiz.length} · Drills: ${courseModule.drills.length}` +
      (courseModule.practice ? ` · Practice tasks: ${courseModule.practice.length}` : ''),
  );
  if (courseModule.status === 'outline' && courseModule.plannedAnimations?.length) {
    push(`- Planned animations: ${courseModule.plannedAnimations.length}`);
  }
  push();
}

writeFileSync(join(process.cwd(), 'COVERAGE.md'), `${lines.join('\n')}\n`);
console.log(`COVERAGE.md written (${lines.length} lines)`);
